### ISSUE TITLE
weighting across iams

### ISSUE THREAD

**Issue by manorman5** [jrising/prospectus-tools#13]
@mayaanorman question: I interpreted from your code that you assign/normalize weights simply based on the files present in the target directory. So, if the target directory is complete (for a given ssp/rcp combo all 66 (33*2) subdirectories have all their files), each iam gets an equal weight in the final mixture distribution. Is that correct?

@jrising response: First, from your previous email: We do not give all models the same weight. GCMs are weighted according to Jiacan's weighting scheme. These are in /shares/gcp/climate/BCSD/SMME/SMME-weights/[rcp]_SMME_weights.tsv.
Maybe that's the reason for discrepancies?

**Comment by manorman5** [comment]
Yes, I am using your get_weights() function from lib/weights.py to load a given rcp/gcm’s weight. Will that give me the right weights? @jrising

**Comment by manorman5** [comment]
My original question was: do you evenly weight iams? @jrising Sorry for being unclear before.

**Comment by jrising** [comment]
Yes, using `get_weights` will work for GCMs, and we do evenly weight IAMs.

**Comment by manorman5** [comment]
Awesome, thanks @jrising!
