### ISSUE TITLE
memory spike when extracting a single ir time series with uncertainty

### ISSUE THREAD

**Issue by manorman5** [jrising/prospectus-tools#14]
@mayaanorman original comment: Also, extracting the quantiles for ARE.3 used up to 110 MB of memory, which seemed like a red flag to me. I didn't see a similar spike in memory for the region agglomeration quantiles extraction.

@jrising follow up question: How many results do you have? I want to understand the 110 MB in context.

**Comment by manorman5** [comment]
@jrising The memory use spiked to 110 MB, when I was extracting a single impact region from 130 results. I was using this newton.yml config file when I saw the memory spike.

```
results-root: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_income_spline_GMFD
deltamethod: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_income_spline_GMFD_dm
output-dir: /shares/gcp/social/parameters/energy/extraction/median_delta_method
file-organize: [rcp, ssp]
do-montecarlo: no
region: ARE.3
column: rebased
evalqvals: [0.05, 0.5, 0.95]
output-format: edfcsv
```
The command I used to call this newton.yml was: `python quantiles.py energy/newton.yml FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline -FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline-histclim`

**Comment by jrising** [comment]
Okay. The expected size for this operation would be more like 20 MB, but `quantiles.py` has a nested dictionary system that could explain the rest of the memory use.

Since the expected maximum number of results for energy is 9 * 2 * 33 = 594, and assuming that everything scales linearly, this doesn't even get into multiple GBs. So, I think we can declare this a non-issue.

**Comment by manorman5** [comment]
Whoops, I had a units issue. My bad @jrising . I meant 110 GB!!!!! 40% of the available memory.

**Comment by jrising** [comment]
Why can't I find this directory? I'm looking on Sacagawea for `/shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_income_spline_GMFD`, but it's not there. I thought things we set up to mirror between Battatu and Sacagawea. Have you run into this before?

**Comment by manorman5** [comment]
We are still in the process of moving all projections from sacagawea to battuta, so we haven't set up  the symbolic link on sac to the battuta outputs yet. On sac you can find the files at `/mnt/battuta_shares/gcp/` or you can find the results at the path above on battuta.

**Comment by brews** [comment]
I'm having trouble reproducing this on sac. I couldn't get resident memory to bounce above ~170 MB, even after poking it with very sharp sticks. I used the same configs as above (adjusted for sac paths), pulling from /mnt/battuta_shares/.

Yo, @mayaanorman are you able to get the memory spike reliably after running this a couple times, back to back?

**Comment by manorman5** [comment]
@brews hey! I've never not seen the memory spike when calling this config on battuta with the following command: `python quantiles.py <path to config> FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline -FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline-histclim`
Let me try running this from sac and see if i dont have the memory spike.

**Comment by manorman5** [comment]
I see the same memory spike on sac... I'm really not sure why I see it and you don't though. Let me know if there are other forms of documentation I can provide!

**Comment by brews** [comment]
@mayaanorman Okay, let's check this out. How are you seeing or measuring the spike exactly?

**Comment by manorman5** [comment]
@brews I'm monitoring my job with htop.

**Comment by brews** [comment]
Thanks, @mayaanorman! Could you please rerun the job as this:

```
/usr/bin time -v python quantiles.py <path to config> FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline -FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline-histclim
```

and then copy-n-paste the last little bit of the output here?

My output looks something like this:

```
...
        Command being timed: "python quantiles.py newton.yml FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline -FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline-histclim"
        User time (seconds): 57.02
        System time (seconds): 6.15
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:03.18
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 171316
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 598537
        Voluntary context switches: 10218
        Involuntary context switches: 641858
        Swaps: 0
        File system inputs: 0
        File system outputs: 120
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by manorman5** [comment]
hi @brews ! Sorry for the delay. I ran the command below because `/usr/bin time` at the beginning of the command didn't work for me. Let me know if that's an issue.
```
/usr/bin/time -v python quantiles.py <path to config> FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline -FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline-histclim
```
Here's my output:
```
        Command being timed: "python quantiles.py energy/newton_test.yml FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline -FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline-histclim"
        User time (seconds): 150.91
        System time (seconds): 311.59
        Percent of CPU this job got: 75%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 10:15.87
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 120154452
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 2
        Minor (reclaiming a frame) page faults: 127857508
        Voluntary context switches: 1010431
        Involuntary context switches: 2573472
        Swaps: 0
        File system inputs: 472061536
        File system outputs: 48
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by brews** [comment]
@mayaanorman Nice. Yup, that was my mistake typing that command out. This is exactly what I wanted. Great work.

Would you please also paste the output from running `pip list` in the same environment? Annd please remind me which branch of prospectus-tools you're working off of for this output ^

**Comment by manorman5** [comment]
Sweet! glad i could help. I'm on the vcvinfo branch. Here's my pip list output: 
```
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
alabaster (0.7.12)
Babel (2.6.0)
backports-abc (0.5)
backports.functools-lru-cache (1.5)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.5.0.1)
bkcharts (0.2)
bokeh (0.12.7)
boto (2.49.0)
boto3 (1.9.131)
botocore (1.12.131)
Bottleneck (1.0.0)
certifi (2016.2.28)
chest (0.2.3)
Click (7.0)
cloudpickle (0.4.0)
construct (2.5.3)
cycler (0.10.0)
dask (0.11.1)
datafs (0.7.1)
distributed (1.18.1)
docutils (0.14)
fair (1.3.6)
fs (0.5.5a1)
future (0.17.1)
futures (3.1.1)
gevent (1.0.1)
gevent-websocket (0.9.3)
greenlet (0.4.12)
h5py (2.9.0)
haystack (0.42)
HeapDict (1.0.0)
imagesize (1.1.0)
impactcommon (0.1, /home/manorman/repos/impact-common)
impactlab-tools (0.3.1, /home/manorman/repos/impactlab-tools)
impactlab-user (0.1.8)
Jinja2 (2.9.6)
jmespath (0.9.4)
joblib (0.13.2)
jrnr (0.2.2)
kiwisolver (1.1.0)
locket (0.2.0)
MarkupSafe (1.0)
matplotlib (2.2.4)
MetaCSV (0.1.0)
msgpack-python (0.4.8)
netCDF4 (1.2.9)
numpy (1.15.1)
openest (0.1, /home/manorman/repos/open-estimate)
packaging (19.0)
pandas (0.23.1)
partd (0.3.8)
patsy (0.5.0)
pefile (2019.4.18)
pip (9.0.1)
psutil (5.2.2)
Pygments (2.3.1)
pyparsing (2.4.0)
python-dateutil (2.7.3)
python-ptrace (0.9.3)
pytz (2017.2)
PyYAML (3.12)
requests (2.14.2)
s3transfer (0.2.0)
scipy (1.1.0)
seaborn (0.9.0)
setuptools (36.4.0)
simpy (3.0.11)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
sortedcontainers (1.5.7)
Sphinx (1.8.5)
sphinx-rtd-theme (0.4.3)
sphinxcontrib-websupport (1.1.0)
statistics (1.0.3.5)
statsmodels (0.9.0)
subprocess32 (3.5.4)
tblib (1.3.2)
toolz (0.8.2)
tornado (4.5.2)
typing (3.6.6)
ujson (1.33)
urllib3 (1.24.2)
wheel (0.29.0)
xarray (0.9.6)
zict (0.1.2)
You are using pip version 9.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by brews** [comment]
Excellent! I replicated the the spike. I should be able to run with this and dig in. Thanks again!

**Comment by brews** [comment]
Annnd I'm going to bet all the tea leaves in London that this spikes in the same place as  https://github.com/jrising/prospectus-tools/issues/15#issuecomment-534914543. I missed that this was in `vcvinfo` and but now some of the latest commits to master now lead me to the spike.

Trying to nail down exactly why all the netCDF data is persisting in memory.

**Comment by manorman5** [comment]
Great, I'm glad you were able to replicate the memory spike! thanks for working on this.

**Comment by brews** [comment]
My work around from https://github.com/jrising/prospectus-tools/issues/15#issuecomment-535612223 solves the memory leak for single region runs. It takes longer to run but it doesn't explode.

We do gobble a great deal of memory if I remove the 'regions' section from the run config. In my last test it allocated around +50GB before I killed it. It doesn't _explode_ to the extent that we saw earlier. I'll let it run this morning (under a careful eye) to see how far it'll go.

This seems large to me. @jrising Should we expect these kinds of sizes with the deltamethod if we consume all regions? Just asking before I go on a wabbit hunt for another memory leak...

**Comment by brews** [comment]
Just killed it at +103 GB. Output is attached. 

[testrun_out.txt](https://github.com/jrising/prospectus-tools/files/3682130/testrun_out.txt)

**Comment by jrising** [comment]
I think we're talking about 24378*81*120*8*130 bytes = 230 GB for this operation. Half of that if you just do 1 RCP. So that seems about right.

**Comment by brews** [comment]
Okay, it peaks at 114 GB, but takes hours-ish (though, I had to run it with `nice`).

I'll run this again during off-hours and see if I can't attach a profiler. It might be nice to see where we are spending this time. If this memory leak is actually solved I'll clean up my solution and put it into a PR.

Will follow up.

**Comment by brews** [comment]
Hooray! I am free and nobody is on the server! 

Let me quickly rebase my workaround and test this out.

The "sic_mad_hax" branch:

```
        User time (seconds): 180.89
        System time (seconds): 272.29
        Percent of CPU this job got: 65%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 11:31.81
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 1309296
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 65
        Minor (reclaiming a frame) page faults: 97132540
        Voluntary context switches: 42185
        Involuntary context switches: 1041838
        Swaps: 0
        File system inputs: 378261656
        File system outputs: 96
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

Current master branch on the same problem:
```
        User time (seconds): 176.12
        System time (seconds): 275.77
        Percent of CPU this job got: 64%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 11:38.25
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 119724168
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 288
        Minor (reclaiming a frame) page faults: 93184295
        Voluntary context switches: 46396
        Involuntary context switches: 1129083
        Swaps: 0
        File system inputs: 464203096
        File system outputs: 96
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

Thats 119.7 GB vs 1.3 GB max memory footprint. Looks like the workaround is doing its job.

Here are the output files

- master branch: [master.tar.gz](https://github.com/jrising/prospectus-tools/files/3770276/master.tar.gz)
- "sic_mad_hax": [sic_mad_hax.tar.gz](https://github.com/jrising/prospectus-tools/files/3770277/sic_mad_hax.tar.gz)

sorry @mayaanorman, I let this issue get a bit stale, do you still have need for the workaround?

**Comment by brews** [comment]
The above was run with `python quantiles.py newton.yml FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline -FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline-histclim`

"newton.yml" contains: 

```
results-root: /mnt/battuta_shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_income_spline_GMFD
deltamethod: /mnt/battuta_shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_income_spline_GMFD_dm
output-dir: parameters/energy/extraction/median_delta_method
file-organize: [rcp, ssp]
do-montecarlo: no
region: ARE.3
column: rebased
evalqvals: [0.05, 0.5, 0.95]
output-format: edfcsv
```
