### ISSUE TITLE
Add the option to choose SSP in the config/command

### ISSUE THREAD

**Issue by brews** [jrising/prospectus-tools#17]
From RA suggestion meeting:

@trinetta  suggested adding the ability to choose SSP in the YML configs or commands. We already have a similar feature for IAM and RCP.

I am assured that this would be lit.

This is moved from the `impact-calculation` issue here: https://gitlab.com/ClimateImpactLab/Impacts/impact-calculations/issues/24#note_224050598.

**Comment by brews** [comment]
@mayaanorman Asked about the timeline for this. I don't think I'll be able to get this in the next week.



As for this, @mayaanorman :

> I currently error out for full uncertainty extraction for ssps where I only have point estimate output and not delta method output.

This feels like a we need to post a new issue for this. @jrising, is this something that should work?

**Comment by manorman5** [comment]
I think this error I highlighted may just be a branch issue on my end. I'll let you know if there is something I think you need to address.
