### ISSUE TITLE
can't extract the mean with full uncertainty quantiles

### ISSUE THREAD

**Issue by manorman5** [jrising/prospectus-tools#18]
Hi @jrising and @brews, using the config below results in the error message below. The error does not arise when I do not have 'mean' in my `evalqvals` parameter.  It would be much more convenient for me, if I could extract the mean along with the quantiles which reflect full uncertainty; however, if this is a lot more work for you, don't worry about it!!!!!!!!!!!!!!! really. 

config: 
```
results-root: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD
deltamethod: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD_dm
output-dir: /shares/gcp/social/parameters/energy/extraction/multi-models/rationalized_code/break2_Exclude_all-issues_semi-parametric/TINV_clim_income_spline_GMFD/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD
file-organize: [ssp, rcp]
do-montecarlo: no
only-models: all
column: rebased
evalqvals: ['mean', .5, 0.05, 0.95, 0.10, 0.90, 0.75, 0.25]
output-format: edfcsv
```
error message: 
```
/shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_income_spline_GMFD_dm/median/rcp85/MPI-ESM-LR/low/SSP3
Observations: 31092
Creating file: ('SSP3', 'rcp85')
Outputing row: (u'', 1981)
/home/manorman/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/manorman/.local/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/home/manorman/.local/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/home/manorman/.local/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:1738: RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= self.b) & cond0
Traceback (most recent call last):
  File "quantiles.py", line 111, in <module>
    writer.writerow(list(rowstuff) + list(distribution.inverse(encoded_evalqvals)))
  File "/home/manorman/repos/prospectus-tools/gcp/extract/lib/weights_vcv.py", line 49, in inverse
    roots.append(brentq(func, left, right))
  File "/home/manorman/.local/lib/python2.7/site-packages/scipy/optimize/zeros.py", line 510, in brentq
    r = _zeros._brentq(f,a,b,xtol,rtol,maxiter,args,full_output,disp)
RuntimeError: Failed to converge after 100 iterations.
```

**Comment by brews** [comment]
@mayaanorman Nice, thanks for the report. Can you confirm what branch you're working from?

**Comment by manorman5** [comment]
@brews I got this error when working on the master branch.

**Comment by jrising** [comment]
That error message is happening just because I haven't implemented means for the "parallel delta method" mode. It's something that we can add, but there are some other GCP priorities on my plate before this. The math is easy though: we should just take a weighted mean, where the weight is the product of the inverse variance and the GCM model weight.

**Comment by brews** [comment]
Thanks, James. Removing the bug tag and marking this as a feature request.

I have other issues to tackle over the next week or two so this is lower priority for me as well.

**Comment by manorman5** [comment]
@jrising if you could get to it when you have time that would be awesome! I would like to clarify though if the lack of mean extraction functionality for the "parallel delta method" mode is a product of how you've set up the code or a conceptual piece I am confused about. 

I was under the impression the mean of the distribution that reflects climate and statistical uncertainty is equivalent to the mean of the distribution that only reflects climate uncertainty. Thus, in my mind (which knows very little about how you've set up the code), outputting the mean of the full uncertainty distribution doesn't require any implementation of conceptual ideas.

**Comment by jrising** [comment]
Okay, so it sounds like there are two things we need to get on the same page about, before I do any implementing.

1. Do we agree on the math of how to do an average in this case? It sounds like no. Your claim is that mean = (\sum_g w_g x_g) / (\sum_g w_g), where g is the GCM. Although I haven't thought about it very much, I think it should be mean = (\sum_g w_g x_g / var(x_g)) / (\sum_g w_g / var(x_g)). Would it make sense for you to set up a monte carlo example, and show which one (if either) works correctly?

2. I don't know what it is that you want to clarify, to understand why there is a lack of mean functionality. It sounds like "I haven't implemented it" isn't the answer you're looking for. Probably easier to talk about this one by voice, if it's important to you.

**Comment by manorman5** [comment]
Hi @jrising,

I totally agree that we need to agree on point/question 1. I think point 2 is just a product of the fact that I thought there was consensus that the mean across climate uncertainty equaled the mean across full uncertainty, but there isn't :). Thus, I don't think we need to or should address point 2.

In respect to question 1, Andy and Ashwin have already run a monte carlo and worked out the math for something related (I believe!!!), so I will start an email chain with them and you to discuss this topic.

All the best,
Maya

**Comment by manorman5** [comment]
Ashwin will email you James about how to average in this case.
