### ISSUE TITLE
`get_regions` no longer handles `countries` and `funds`

### ISSUE THREAD

**Issue by jrising** [jrising/prospectus-tools#27]
PR #26 includes a change to the logic in `get_regions`. There are a few problems with this change:
 - If the regions configuration option includes `countries` or `funds`, these will not be properly handled.
 - The function will return `[]` to mean "all regions" if `allregions` is None, and will return a list of all of the regions if it is given to it. That seems like confusing logic, when one of the points of `get_regions` is to abstract away the configuration setup and return a consistently usable result.

Probably the easiest solution is to remove the changes to `get_regions`, and move the call to `get_regions` to inside of `read_region`, at which point the regions list will be available. 

Also the line `if target_regions == ['all'] or target_regions == []:` should be replaced with a call to `is_allregions`.

**Comment by brews** [comment]
Got it! Thanks for the issue.

**Comment by brews** [comment]
@jrising I didn't even catch the bit about "countries" or "funds" or how `regions` handles  a "global" option. I've been looking at the documentation in prespectus-tools/gcp/extract/config-docs.md, can I find these details elsewhere?

Edit: Is there another function or method that breaks down the funds or countries into indexes or the regions that are needed from the netCDF data?

**Comment by brews** [comment]
@jrising I feel like these changes are adding too much magic into the `read_region` function.  As it is, it takes the netCDF and removes the target regions. Handing it a YAML config to then interpret feels like a separate step that doesn't need to happen every time we read the netCDF file. Just do it once and tell `read_region` what regions to extract. As it is, this is simple to remove or test in the future because it is not entangled with how the yaml is configured or interpreted.

Please correct me if I'm not following you on this or if I've misinterpreted what you're asking. There might be some larger problem that I'm not seeing.

**Comment by TomBearpark** [comment]
Hey both. I am having an issue (/ encountering a bug) when trying to use quantiles.py since PR #26, that i think is related to this thread. 

To reproduce the error - here was the command I used: 
```
python -i quantiles.py <path_to_config>/energy-extract-damagepc-aggregated-price014-median_OTHERIND_total_energy_dm.yml --only-iam=high  --region=global --suffix=_damagepc-price014_median_high_fulladapt-aggregated_dm FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_electricity_TINV_clim_income_spline-price014-aggregated -FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_electricity_TINV_clim_income_spline-histclim-price014-aggregated FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline-price014-aggregated -FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline-histclim-price014-aggregated
```

And here is the contents of that config: 
```
results-root:
  FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline.*: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_income_spline_GMFD_dm
  FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_electricity_TINV_clim_income_spline.*: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD_dm
multiimpact_vcv: /shares/gcp/social/parameters/energy/incspline0719/GMFD/TINV_clim_income_spline/FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_TINV_clim_income_spline-fixed.csv
output-dir: /shares/gcp/social/parameters/energy/extraction/multi-models/rationalized_code/break2_Exclude_all-issues_semi-parametric/TINV_clim_income_spline_GMFD/total_energy/price014pc
file-organize: [ssp, region]
do-montecarlo: no
only-models: all
only-iam: null
deltamethod: true
column: rebased
output-format: valuescsv
```

The error that I get is: 
```
/home/tbearpark/repos/prospectus-tools/gcp/extract/lib/configs.py:38: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(fp)
/home/tbearpark/repos/prospectus-tools/gcp/extract/lib/configs.py:28: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config[chunks[0]] = yaml.load(chunks[1])
/shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD_dm/median/rcp45/surrogate_GFDL-CM3_89/high/SSP3 ...
Failed to read /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD_dm/median/rcp45/surrogate_GFDL-CM3_89/high/SSP3/FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_electricity_TINV_clim_income_spline-price014-aggregated.nc4
Traceback (most recent call last):
  File "/home/tbearpark/repos/prospectus-tools/gcp/extract/lib/results.py", line 163, in sum_into_data
    for region, years, values in bundles.iterate_regions(fullpath, columns[ii], config):
  File "/home/tbearpark/repos/prospectus-tools/gcp/extract/lib/bundles.py", line 147, in iterate_regions
    ii = regions.index(region)
ValueError: '' is not in list
Traceback (most recent call last):
  File "quantiles.py", line 36, in <module>
    data, years = results.sum_into_data(config['results-root'], basenames, columns, config, transforms, vectransforms)
  File "/home/tbearpark/repos/prospectus-tools/gcp/extract/lib/results.py", line 188, in sum_into_data
    exit()
  File "/home/tbearpark/miniconda3/envs/risingverse-py27/lib/python2.7/site.py", line 360, in __call__
    raise SystemExit(code)
```
Note, we are specifying the region (global in this case) through the command, rather than through the contents of the config. 

Please let me know if any of this is unclear, or if there is anything else I can provide on this!

**Comment by TomBearpark** [comment]
To note (posting this after discussion with Brewster about the functionality of the region restriction) in netcdf files with the  `-aggregated` tag (ie those that contain information on agglomerations of impact regions), regions that are not the `global` region are defined using their name, however the global region is identified as `''`. 

So running quantiles.py with the restriction `--region=global` gives results corresponding to the `''` entry in the `aggregated` netcdfs.

**Comment by jrising** [comment]
@brews I think it's fine if you want to keep `read_region` simple (though it's a bit simple for my aesthetics). In that case, how about adding a `read_regions_list` function, which returns the full list of regions, for use at the top of `iterate_regions` for the call to `config.get_regions`?

**Comment by brews** [comment]
@jrising I have the changes you recommended in PR #28. After the discussion with you I implemented most, if not all of your suggestions. 

However, I'm not sure this deals with the issue that the energy sector crew raised. If 'region' is "global" in the config file yaml file, this will not extract the values they expect.  We still need to translate "global" to the region "", akin to @mayaanorman's suggested change in 3678aa6304147b8efa88ee45aaec7ff5aeeeef96? Maybe drop this into `configs.get_regions()`?

Please let me know if I'm missing anything. Thank you.

**Comment by jrising** [comment]
Good point. Let's move the functionality of bundles.py lines 141-142 (on your PR branch) into `get_regions`. Note that since `get_regions` returns a list, you'll have to replace it within the list rather than the way that 141-142 do it.

**Comment by brews** [comment]
This is all getting wrapped (including "global" `region` in PR #28).
