### ISSUE TITLE
Region command line argument issue when using quantiles.py

### ISSUE THREAD

**Issue by TomBearpark** [jrising/prospectus-tools#30]
Hey @brews, 

### Issue 
I have been having problems using quantiles.py to extract impacts for a single region using the command line. 

An example of a command that has this problem is:

```
python -i quantiles.py extract_energy.yml --region=USA --suffix=_impactpc_median_fulladapt-aggregated FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_electricity_TINV_clim_income_spline-aggregated -FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_electricity_TINV_clim_income_spline-histclim-aggregated

```

where `extract_energy.yml` is: 

```
results-root: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD
output-dir: /shares/gcp/social/parameters/energy/extraction/multi-models/rationalized_code/test
file-organize: [ssp, region]
do-montecarlo: no
only-rcp: null
only-ssp: SSP3
only-models: all
only-iam: null
column: rebased
output-format: valuescsv
```

Rather than only extracting impacts for the USA region, this command produces output csvs for all possible regions, which takes a very long time and produces a lot of un-needed data. 

### Working fix
Thanks to maya we have a working solution (that I'm currently using on a separate branch). I'm posting it here in case it's useful... 

- Alter the [get_regions ](https://github.com/jrising/prospectus-tools/blob/08308641427a1a24c5aec7aac769a1e2deeb4a43/gcp/extract/lib/configs.py#L195 )function to include the following logic (that converts the string to a list): 
```
    if isinstance(regions, str):
        regions = [regions]
```
- Use ```--regions=USA``` in the command line arguments. The [documentation ](https://github.com/jrising/prospectus-tools/tree/08308641427a1a24c5aec7aac769a1e2deeb4a43/gcp/extract) currently suggests we should use `--region=USA` , so I'm not sure if our solution here is one that you would want to take up and therfore change the documentation, or if it would be better to make changes to the code so we can continue to use the existing syntax. 

Thanks!
Tom

**Comment by brews** [comment]
Thanks for the issue @TomBearpark! Appreciate the documentation and heads-up.

**Comment by jrising** [comment]
@brews I've tracked this down. You broke this functionality in commit:
https://github.com/jrising/prospectus-tools/commit/2a95b6311d4dbaa918241f42e8a5a8b097642b79

I'm testing putting the functionality back.

**Comment by jrising** [comment]
@TomBearpark I want to keep the distinction between `region`, which takes a string, and `regions` which takes a list of strings. Eventually, if `regions` is given a string, it should treat it like a prefix.

So, my solution was just to add back in the line that handles the `region` config option, here:
https://github.com/jrising/prospectus-tools/pull/31/files
