### ISSUE TITLE
sector specific weights transformation

### ISSUE THREAD

**Issue by emileten** [jrising/prospectus-tools#37]
@brews (again, not sure who to assign, happy if someone can correct me) I have been using, for extracting agriculture results, a specific set of GCM weights that differs from what goes through the extraction in the `master` branch. In order to do so, I've been passed on by the previous RA an update to the two first functions of `weights.py` : 

```
def get_weights_april2016(rcp):
    weights = {}
    if rcp == 'rcp45':
        with open('/shares/gcp/climate/BCSD/SMME/SMME-weights/rcp45_2090_SMME_edited_for_April_2016.tsv', 'rU') as tsvfp:
            reader = csv.reader(tsvfp, delimiter='\t')
            header = reader.next()
            for row in reader:
                model = row[1].split('_')[0].strip('*').lower()
                weight = float(row[2])
                weights[model] = weight
        weights["pattern4"] = 0 # Explicitly remove (so no messages)
    if rcp == 'rcp85':
        with open('/shares/gcp/climate/BCSD/SMME/SMME-weights/rcp85_2090_SMME_Arg_April2019.tsv', 'rU') as tsvfp:
            reader = csv.reader(tsvfp, delimiter='\t')
            header = reader.next()
            for row in reader:
                model = row[1].split('_')[0].strip('*').lower()
                weight = float(row[2])
                weights[model] = weight
    return weights
def get_weights_march2018(rcp):
    weights = {}
    with open('/shares/gcp/climate/BCSD/SMME/SMME-weights/' + rcp + '_SMME_weights.tsv', 'rU') as tsvfp:
        reader = csv.reader(tsvfp, delimiter='\t')
        header = reader.next()
        for row in reader:
            model = row[1].strip('*').lower()
            if '_' in model:
                model = 'surrogate_' + model
            weight = float(row[2])
            weights[model] = weight
    if rcp == 'rcp45':
        weights["surrogate_gfdl-esm2g_06"] = 0 # Explicitly remove (so no messages)
    if rcp == 'rcp85':
        weights["access1-0"] = 0
        weights["ipsl-cm5a-lr"] = 0.036
        weights["ipsl-cm5a-mr"] = 0.036
        weights["csiro-mk3-6-0"] = 0.036
        weights["canesm2"] = 0.036
        weights["bnu-esm"] = 0.036
    return weights
```

Note the differences are for `rcp85` -- the file used is different, and the changes applied to what it contains as well. 

This lives only in my local version of the repository. I would like to do this the proper way (my bad for not writing this issue earlier). Can I do so with the existing code? Or do we need some development to allow for this?

Thank you very much !

**Comment by jrising** [comment]
@emileten I need some background here. Why is agriculture using a different set of weights than other sectors, and where did these weights come from?

Also, on the code side, I'm confused about some issues:
 - In `get_weights_april2016`, the only difference I see between the two code chunks is the filename. Can the rest of the code repetition be deleted?
 - In `get_weights_march2018`, shouldn't we be updating the file rather than hard-coding these weight changes?

**Comment by emileten** [comment]
@jrising, thank you. Here are answers to your questions : 
- about your first question, I have part of the background only. `access1-0` in `rcp85` is dropped because of extreme precipitation values, but I don't know about the others. Let me do some research (in particular ask andy), and I will get back to you.
- regarding the second question, you are right about the only difference and yes it can be deleted (I am using the code that was handed over). 
- yes, that would be better, but we don't want to write these changes to the files if those are agriculture specific, no ?

**Comment by emileten** [comment]
@jrising so indeed, weights in agriculture are different because it was decided to drop `access1-0` in `rcp85` (extreme precip). This influenced the weights of the other models. Jiacan had computed the weights for all the models in `rcp85` with that updated, you can see [this slack link](https://climateimpactlab.slack.com/archives/C2CHW1KCG/p1584456833020100). Now I don't know why there is also a hard coded weights update in that code, on top of the file for `rcp85` being different. Models that are in the same bin as `access1-0` are being updated in that hard coded part, so it's linked to the same update.

**Comment by andyhultgren** [comment]
@jrising @emileten  Emile is right, ACCESS1-0 is dropped for RCP 8.5 due to implausible precip values, and Jaican produced new RCP8.5 SMME weights to account for this.

I don't know why the hardcoded re-weighting is also in the second version of this function.  I didn't realize it was there (though, a confused-version of my past self may well have asked for it, who knows). At any rate, I don't think those lines should be used; we should just be using Jaican's weights -- her original weights for RCP 4.5, and her updated weights for RCP 8.5.

To be clear, these are the lines that I think are wrong:
```    
if rcp == 'rcp85':
        weights["access1-0"] = 0
        weights["ipsl-cm5a-lr"] = 0.036
        weights["ipsl-cm5a-mr"] = 0.036
        weights["csiro-mk3-6-0"] = 0.036
        weights["canesm2"] = 0.036
        weights["bnu-esm"] = 0.036
```

Based on a very quick look which we should confirm, it looks (??) to me like `get_weights_april2016(rcp)` implements this correctly.

**Comment by jrising** [comment]
Okay, then I definitely think that we should transition away from this code. One solution is to just delete or move away all of the `access1-0` results (taking advantage of the default behavior we discussed in #36). I think that's pretty sensible, because it handles the problem at the source: we actually should never have made the `access1-0` results in the first place once we realized that we don't want to use them.

I can imagine you saying "We want those results for robustness checks, even if we don't normally use them." In that case, we do have an existing config option for this kind of case: `only-models: [....]` which takes a list of GCMs, and any GCM that's not on that list gets dropped. We could also add a config option like `ignore-gcms: ...` which takes a list of GCMs to drop.

**Comment by jrising** [comment]
Oh, I just read @emileten's comment that we do need to adjust the weights of other models, in light of dropping `access1-0`. Okay, then I propose the following:
 - We implement `ignore-gcms`, for convenience.
 - We write out this new set of weights to a file, named something like `rcp85_SMME_weights-no-access1-0.tsv`.
 - Whether `ignore-gcms` or `only-models` is used, the code looks at the resulting list of models, and look for a corresponding weights file, e.g., of the form `<RCP>_SMME_weights-no-<GCMs>.tsv`. If that exists, we use it. If not, we give a warning and then use the default set of weights.

**Comment by emileten** [comment]
@jrising thank you. After testing this code above in isolation it turns out it is not doing anything wrong, it's just very confusing.  the values `get_weights_april2016` returns are the weights we want, with the file difference, and the hard coded weights written in `get_weights_march2018` are there because the function overwrites this difference. I.e ag weights differences are only what you see in this hard coded part.

We definitely don't want to keep this code. I understand what you are suggesting @jrising. Do you need any help to implement that?

**Comment by andyhultgren** [comment]
I totally agree this implementation should be cleaned up for code
accessibility / maintenance going forward. It is pretty confusing in the
current setup and I didn't realize it had been done like this! Thank you
@emileten <https://github.com/emileten> for testing it and getting to the
bottom of it. Given that the current (confusing) implementation works, I'm
totally ok with this being a lower priority item, but @jrising
<https://github.com/jrising> of course up to you.

Also, just to be sure we're all on the same page, we do use ACCESS1-0, but
only for RCP4.5 and not RCP8.5.

**Comment by jrising** [comment]
@emileten Okay, let's do this. Can you produce this as a stand-alone weights file? I'll work on the code.

**Comment by jrising** [comment]
Okay, I've started a PR. What I am currently not handling is @andyhultgren's comment that the model should only be dropped for one of the RCPs.

Under my PR, which follows my proposal above, you could get the desired behavior by separately calling `quantiles.py` for RCP 4.5 and 8.5, with the `drop-models` option (I changed the proposed name from from `ignore-models` to `drop-models`) only for RCP 8.5.

But unless you are already calling quantiles.py separately for the two RCPs, I think that this will be a nuisance. So we need an intuitive configuration scheme for saying "I only want to ignore this model for a given RCP".

My proposal is that the entries in `only-models` and `drop-models` can either be direct model names-- in which case, it applies to all RCPs-- or can be entries of the form `<rcp>/<model>`. So, in your case, you would use:
```
drop-models: [rcp85/access1-0]
```

Thoughts?

**Comment by emileten** [comment]
> @emileten Okay, let's do this. Can you produce this as a stand-alone weights file? I'll work on the code.

@jrising great thank you ! The file is actually the one already referenced in the top of the code above, i.e : `'/shares/gcp/climate/BCSD/SMME/SMME-weights/rcp85_2090_SMME_Arg_April2019.tsv'`.

**Comment by emileten** [comment]
> Okay, I've started a PR. What I am currently not handling is @andyhultgren's comment that the model should only be dropped for one of the RCPs.
> 
> Under my PR, which follows my proposal above, you could get the desired behavior by separately calling `quantiles.py` for RCP 4.5 and 8.5, with the `drop-models` option (I changed the proposed name from from `ignore-models` to `drop-models`) only for RCP 8.5.
> 
> But unless you are already calling quantiles.py separately for the two RCPs, I think that this will be a nuisance. So we need an intuitive configuration scheme for saying "I only want to ignore this model for a given RCP".
> 
> My proposal is that the entries in `only-models` and `drop-models` can either be direct model names-- in which case, it applies to all RCPs-- or can be entries of the form `<rcp>/<model>`. So, in your case, you would use:
> 
> ```
> drop-models: [rcp85/access1-0]
> ```
> 
> Thoughts?

@jrising Regarding this, I am personally ok with either. I can use the current state of the PR without much trouble provided I have the ability to pass `drop-models=None` (or anything that is used as a 'drop nothing' value), because I use a wrapper script that is looping over `rcp`s and calling `quantiles.py` with the `only-rcp` option. 

Your second suggestion sounds more general though, and easy to use.

**Comment by jrising** [comment]
Okay, then let's not create a new syntax for a future use case now. You can either just leave the `drop-models` option out, or set it to `none` for RCP 4.5.

I've made a branch and PR for this: https://github.com/jrising/prospectus-tools/pull/39

Unfortunately, changes on the server have broken my python 2 environment, so I have not been able to properly test this. Your help on this would be appreciated. Can you run `tests/test_gcmfilter.py`, in the `extract` directory, on the `modelweights` branch? I'm hoping that produces no exceptions.

Then, you will need to rename `rcp85_2090_SMME_Arg_April2019.tsv` to `rcp85_SMME_weights-no-access1-0.tsv`, and you can test it. Make sure it doesn't complain about not being able to find the weights file.

**Comment by emileten** [comment]
Hi @jrising. I ran the tests and the last one failed -- I added a comment in the commit in order to clarify.

**Comment by emileten** [comment]
Hey @jrising, let me know if you need any further help in these changes! We will be handing over the task of running these codes across team members so it would be great if I could be able to use this functionality. 

Thank you very much !

**Comment by emileten** [comment]
@jrising (@andyhultgren I you have any idea...) I am sorry that I have to resume this thread. I noticed a problem with what we merged (which doesn't affect any past result). I am happy to solve the problem myself, but i find these weights versioning very hard to understand, so if I could get some help to understand the background in more details than last time, it would be great. Let me know if you are not aware of these details, in which case I guess I should ask the climate team. 


I will start with the question. There are three kinds of files as of now in `/shares/gcp/climate/BCSD/SMME/SMME-weights`, and each contains different sets of model names. Below each file path and the models it contains : 

`/shares/gcp/climate/BCSD/SMME/SMME-weights/rcp85_SMME_weights.tsv` :  
```
 [1] "access1-0*"      "bcc-csm1-1"      "bnu-esm*"        "canesm2_89"
 [5] "canesm2_94"      "canesm2_99"      "canesm2*"        "ccsm4"
 [9] "cesm1-bgc*"      "cnrm-cm5"        "csiro-mk3-6-0"   "gfdl-cm3_89"
[13] "gfdl-cm3_94"     "gfdl-cm3_99"     "gfdl-cm3*"       "gfdl-esm2g_01"
[17] "gfdl-esm2g_06"   "gfdl-esm2g_11"   "gfdl-esm2g*"     "gfdl-esm2m"
[21] "inmcm4*"         "ipsl-cm5a-lr"    "ipsl-cm5a-mr*"   "miroc-esm-chem*"
[25] "miroc-esm*"      "miroc5*"         "mpi-esm-lr"      "mpi-esm-mr*"
[29] "mri-cgcm3_01"    "mri-cgcm3_06"    "mri-cgcm3_11"    "mri-cgcm3*"
[33] "noresm1-m*"
```

`/shares/gcp/climate/BCSD/SMME/SMME-weights/rcp85_2090_SMME_edited_for_April_2016.tsv`
```
 [1] "access1-0*"        "bcc-csm1-1"        "bnu-esm*"
 [4] "canesm2*"          "ccsm4"             "cesm1-bgc*"
 [7] "cnrm-cm5"          "csiro-mk3-6-0"     "gfdl-cm3*"
[10] "gfdl-esm2g*"       "gfdl-esm2m"        "inmcm4*"
[13] "ipsl-cm5a-lr"      "ipsl-cm5a-mr*"     "miroc-esm-chem*"
[16] "miroc-esm*"        "miroc5*"           "mpi-esm-lr"
[19] "mpi-esm-mr*"       "mri-cgcm3*"        "noresm1-m*"
[22] "pattern1_1.005*"   "pattern2_1.005*"   "pattern28_89.000*"
[25] "pattern29_89.000*" "pattern3_6.000*"   "pattern30_94.000*"
[28] "pattern31_94.000*" "pattern32_98.995*" "pattern33_98.995*"
[31] "pattern4_6.000*"   "pattern5_11.000*"  "pattern6_11.000*"
```

This is the one produced by Jiacan last year that drops `access1-0` and upweights the other models in the same bin : 
`/shares/gcp/climate/BCSD/SMME/SMME-weights/rcp85_2090_SMME_Arg_April2019.tsv`
```
 [1] "bcc-csm1-1"        "bnu-esm*"          "canesm2*"
 [4] "ccsm4"             "cesm1-bgc*"        "cnrm-cm5"
 [7] "csiro-mk3-6-0"     "gfdl-cm3*"         "gfdl-esm2g*"
[10] "gfdl-esm2m"        "inmcm4*"           "ipsl-cm5a-lr"
[13] "ipsl-cm5a-mr*"     "miroc-esm-chem*"   "miroc-esm*"
[16] "miroc5*"           "mpi-esm-lr"        "mpi-esm-mr*"
[19] "mri-cgcm3*"        "noresm1-m*"        "pattern1_1.005*"
[22] "pattern2_1.005*"   "pattern27_89.000*" "pattern28_89.000*"
[25] "pattern29_94.000*" "pattern3_6.000*"   "pattern30_94.000*"
[28] "pattern31_98.995*" "pattern32_98.995*" "pattern4_6.000*"
[31] "pattern5_11.000*"  "pattern6_11.000*"
```


My questions are : 1/ why do files (1) and (2) not contain the surrogate models (e.g. `canesm2_94`) ? 2/ why does the file (1) not contain the  `pattern_...` models ? 

Now the problem : as I said the only file containing the surrogate models weights is the (1). As a consequence, if I try to use `drop-models: access1-0`, which behind the scene loads the file (2) and updates its data with the file (3), I get at the end of the day weights that do not contain the surrogate models. 

Thanks !

**Comment by jrising** [comment]
The pattern and surrogate models are the same thing. Their naming convention changed mid-stream, without a corresponding change in the climate data, so I combine the 2018 (rcp85_SMME_weights.tsv) and 2016 (rcp85_2090_SMME_edited_for_April_2016.tsv) to make sure that I capture both names. So, you get the default weights for those.

If you use the `drop-models: access1-0` option, the code looks for a file `rcp85_2090_SMME_no_access1-0.tsv`. That file doesn't exist in the directory. I think the plan was for you to rename `rcp85_2090_SMME_Arg_April2019.tsv` to `rcp85_SMME_weights-no-access1-0.tsv`. When you do that, just add in the "canesm2_89"-style surrogate names, if that is the naming convention your results are produced with. You can rename the pattern... names to the surrogate names. Just make sure that the last digits line up.
