### ISSUE TITLE
Mortality extraction of single model MC run not computing `fulladaptcosts` as sum of `fulladapt` and `costs`

### ISSUE THREAD

**Issue by StefanKlos** [jrising/prospectus-tools#43]
Pretty much, running the [base mortality extraction config](https://gitlab.com/ClimateImpactLab/Impacts/mortality/-/blob/fix-extract/2_projection/2_run_projections/extract/extract_mortality.yml) on the CCSM4 run is giving me `fulladaptcosts` values that do not equal the sum of `fulladapt` and `costs`. The shell script I am running is [here](https://gitlab.com/ClimateImpactLab/Impacts/mortality/-/blob/fix-extract/2_projection/2_run_projections/extract/extract_mortality_impacts.sh) where `CCSM4_MC` is the root of the single climate model-495 draw run. 

From `/repos/mortality/2_projection/2_run_projections/extract` and in the environment `risingverse-py27`, the code I ran was: `bash extract_mortality_impacts.sh extract_mortality.yml`

I used this same config (with relevant paths) to successfully produce the MC and median run extracted files, and modified the folder structure of the raw CCSM4 projections to match that of a MC.  Other than `fulladaptcosts`, the rest of the extraction files look good (ie `noadapt + incbenefits + climbenefits = fulladapt` ). I also confirmed the validity of the underlying MC files (which look correct) as do the regional aggregations.

Using the same script as above, I then tried 2 other extractions, one turning on `only-models = CCSM4` (given that's the only model there anyway), then one where `do-gcmweights = no`. Both produced the exact same results as running the base config on the `CCSM4_MC` folder. 

I've been looking at `quantiles.py` to see how exactly `fulladaptcosts` are calculated, and don't immediately see anything that would make them not add up in a scenario where the only difference between and MC and this run is there is only one climate model folder in `raw/{batch}/{rcp}/{model}/{iam}/{SSP}/`

**Comment by jrising** [comment]
So, as I understand your shell script, when `scn = fulladaptcosts`, you are asking `quantiles.py` to calcuate:

`BASENAME-combined-aggregated.nc4 - BASENAME-combined-histclim-aggregated.nc4 + BASELINE-combined-costs-aggregvated.nc4`
which then takes the `rebased` column from the first two and adds the `costs_ub` column from the last one (divided by 1e5).

Then, you're comparing that to the sum of
1. `BASENAME-combined-aggregated.nc4 - BASENAME-combined-histclim-aggregated.nc4` (`rebased` from those)
2. `BASENAME-combined-costs-aggregated.nc4` (`costs_ub` from that)

Is that correct?

When you compared these two, did you account for the normalization that happens in quantiles.py for cost files when you don't specify a column? (That is, the division by 1e5?)

**Comment by StefanKlos** [comment]
This ended up being a problem with the adaptation costs source files that was fixed by rerunning aggregation with a modified configuration

**Comment by jrising** [comment]
@StefanKlos Glad to hear you tracked it down!
